[package]
name = "mrg32k3a-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "mrg32k3a_core"
crate-type = ["cdylib"]

[dependencies]
mrg32k3a-rs = { path = "../mrg32k3a-rs" }
pyo3 = "0.25.0"
